namespace Clinica_Herramientas_2.Infrastructure.GUI.Support
{
    partial class ProcedureForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.grpProcedure = new System.Windows.Forms.GroupBox();
            this.txtSpecialistTypeId = new System.Windows.Forms.TextBox();
            this.chkRequiresSpecialist = new System.Windows.Forms.CheckBox();
            this.txtFrequency = new System.Windows.Forms.TextBox();
            this.txtCost = new System.Windows.Forms.TextBox();
            this.txtName = new System.Windows.Forms.TextBox();
            this.txtId = new System.Windows.Forms.TextBox();
            this.lblSpecialistTypeId = new System.Windows.Forms.Label();
            this.lblFrequency = new System.Windows.Forms.Label();
            this.lblCost = new System.Windows.Forms.Label();
            this.lblName = new System.Windows.Forms.Label();
            this.lblId = new System.Windows.Forms.Label();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.grpProcedure.SuspendLayout();
            this.SuspendLayout();
            this.grpProcedure.Controls.Add(this.txtSpecialistTypeId);
            this.grpProcedure.Controls.Add(this.chkRequiresSpecialist);
            this.grpProcedure.Controls.Add(this.txtFrequency);
            this.grpProcedure.Controls.Add(this.txtCost);
            this.grpProcedure.Controls.Add(this.txtName);
            this.grpProcedure.Controls.Add(this.txtId);
            this.grpProcedure.Controls.Add(this.lblSpecialistTypeId);
            this.grpProcedure.Controls.Add(this.lblFrequency);
            this.grpProcedure.Controls.Add(this.lblCost);
            this.grpProcedure.Controls.Add(this.lblName);
            this.grpProcedure.Controls.Add(this.lblId);
            this.grpProcedure.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpProcedure.Location = new System.Drawing.Point(20, 20);
            this.grpProcedure.Name = "grpProcedure";
            this.grpProcedure.Size = new System.Drawing.Size(600, 280);
            this.grpProcedure.TabIndex = 0;
            this.grpProcedure.TabStop = false;
            this.grpProcedure.Text = "Información del Procedimiento";
            this.lblId.AutoSize = true;
            this.lblId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblId.Location = new System.Drawing.Point(20, 30);
            this.lblId.Name = "lblId";
            this.lblId.Size = new System.Drawing.Size(24, 15);
            this.lblId.TabIndex = 0;
            this.lblId.Text = "ID:";
            this.txtId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtId.Location = new System.Drawing.Point(50, 27);
            this.txtId.Name = "txtId";
            this.txtId.Size = new System.Drawing.Size(100, 21);
            this.txtId.TabIndex = 1;
            this.lblName.AutoSize = true;
            this.lblName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblName.Location = new System.Drawing.Point(170, 30);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(55, 15);
            this.lblName.TabIndex = 2;
            this.lblName.Text = "Nombre:";
            this.txtName.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtName.Location = new System.Drawing.Point(231, 27);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(350, 21);
            this.txtName.TabIndex = 3;
            this.lblCost.AutoSize = true;
            this.lblCost.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblCost.Location = new System.Drawing.Point(20, 70);
            this.lblCost.Name = "lblCost";
            this.lblCost.Size = new System.Drawing.Size(42, 15);
            this.lblCost.TabIndex = 4;
            this.lblCost.Text = "Costo:";
            this.txtCost.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtCost.Location = new System.Drawing.Point(68, 67);
            this.txtCost.Name = "txtCost";
            this.txtCost.Size = new System.Drawing.Size(150, 21);
            this.txtCost.TabIndex = 5;
            this.lblFrequency.AutoSize = true;
            this.lblFrequency.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblFrequency.Location = new System.Drawing.Point(240, 70);
            this.lblFrequency.Name = "lblFrequency";
            this.lblFrequency.Size = new System.Drawing.Size(68, 15);
            this.lblFrequency.TabIndex = 6;
            this.lblFrequency.Text = "Frecuencia:";
            this.txtFrequency.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtFrequency.Location = new System.Drawing.Point(314, 67);
            this.txtFrequency.Name = "txtFrequency";
            this.txtFrequency.Size = new System.Drawing.Size(100, 21);
            this.txtFrequency.TabIndex = 7;
            this.chkRequiresSpecialist.AutoSize = true;
            this.chkRequiresSpecialist.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.chkRequiresSpecialist.Location = new System.Drawing.Point(20, 110);
            this.chkRequiresSpecialist.Name = "chkRequiresSpecialist";
            this.chkRequiresSpecialist.Size = new System.Drawing.Size(150, 19);
            this.chkRequiresSpecialist.TabIndex = 8;
            this.chkRequiresSpecialist.Text = "Requiere Especialista";
            this.chkRequiresSpecialist.UseVisualStyleBackColor = true;
            this.chkRequiresSpecialist.CheckedChanged += new System.EventHandler(this.chkRequiresSpecialist_CheckedChanged);
            this.lblSpecialistTypeId.AutoSize = true;
            this.lblSpecialistTypeId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblSpecialistTypeId.Location = new System.Drawing.Point(20, 150);
            this.lblSpecialistTypeId.Name = "lblSpecialistTypeId";
            this.lblSpecialistTypeId.Size = new System.Drawing.Size(120, 15);
            this.lblSpecialistTypeId.TabIndex = 9;
            this.lblSpecialistTypeId.Text = "ID Tipo Especialista:";
            this.txtSpecialistTypeId.Enabled = false;
            this.txtSpecialistTypeId.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtSpecialistTypeId.Location = new System.Drawing.Point(146, 147);
            this.txtSpecialistTypeId.Name = "txtSpecialistTypeId";
            this.txtSpecialistTypeId.Size = new System.Drawing.Size(100, 21);
            this.txtSpecialistTypeId.TabIndex = 10;
            this.btnSave.BackColor = System.Drawing.Color.FromArgb(234, 88, 12);
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSave.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.Location = new System.Drawing.Point(400, 320);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(100, 40);
            this.btnSave.TabIndex = 1;
            this.btnSave.Text = "Guardar";
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.btnCancel.BackColor = System.Drawing.Color.FromArgb(156, 163, 175);
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.Location = new System.Drawing.Point(520, 320);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(100, 40);
            this.btnCancel.TabIndex = 2;
            this.btnCancel.Text = "Cancelar";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(650, 380);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.grpProcedure);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.Name = "ProcedureForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Procedimiento";
            this.grpProcedure.ResumeLayout(false);
            this.grpProcedure.PerformLayout();
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.GroupBox grpProcedure;
        private System.Windows.Forms.Label lblId;
        private System.Windows.Forms.TextBox txtId;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.Label lblCost;
        private System.Windows.Forms.TextBox txtCost;
        private System.Windows.Forms.Label lblFrequency;
        private System.Windows.Forms.TextBox txtFrequency;
        private System.Windows.Forms.CheckBox chkRequiresSpecialist;
        private System.Windows.Forms.Label lblSpecialistTypeId;
        private System.Windows.Forms.TextBox txtSpecialistTypeId;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnCancel;
    }
}

