// <auto-generated />
using System;
using Clinica_Herramientas_2.Infrastructure.Adapters.Output.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinica_Herramientas_2.Migrations
{
    [DbContext(typeof(ClinicaDbContext))]
    [Migration("20251023002033_SeedInitialRRHHUser")]
    partial class SeedInitialRRHHUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Appointment", b =>
                {
                    b.Property<int>("Id1")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id1");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id1"));

                    b.Property<DateTime>("Date1")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date1");

                    b.Property<string>("patient_dni")
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id1");

                    b.HasIndex("patient_dni");

                    b.ToTable("appointment", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.ClinicalResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("clinical_resource", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Invoice", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer")
                        .HasColumnName("invoice_number");

                    b.Property<decimal>("AnnualCopaymentAccumulated")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("annual_copayment_accumulated");

                    b.Property<decimal>("CopaymentAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("copayment_amount");

                    b.Property<decimal>("InsuranceAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("insurance_amount");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invoice_date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<string>("doctor_dni")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("patient_dni")
                        .HasColumnType("character varying(20)");

                    b.HasKey("InvoiceNumber");

                    b.HasIndex("doctor_dni");

                    b.HasIndex("patient_dni");

                    b.ToTable("invoice", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsultationReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("consultation_reason");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("diagnosis");

                    b.Property<string>("Symptoms")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("symptoms");

                    b.Property<string>("doctor_dni")
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("order_number")
                        .HasColumnType("integer");

                    b.Property<string>("patient_dni")
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("doctor_dni");

                    b.HasIndex("order_number");

                    b.HasIndex("patient_dni");

                    b.ToTable("medical_record", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Order", b =>
                {
                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.HasKey("OrderNumber");

                    b.ToTable("order", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.OrderItem", b =>
                {
                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer")
                        .HasColumnName("order_number");

                    b.Property<int>("ItemNumber")
                        .HasColumnType("integer")
                        .HasColumnName("item_number");

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("cost");

                    b.Property<int?>("order_number")
                        .HasColumnType("integer");

                    b.HasKey("OrderNumber", "ItemNumber");

                    b.HasIndex("order_number");

                    b.ToTable("order_item", null, t =>
                        {
                            t.Property("order_number")
                                .HasColumnName("order_number1");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.PatientCareRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TestsPerformed")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("item_number")
                        .HasColumnType("integer");

                    b.Property<int?>("order_number")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("order_number", "item_number");

                    b.ToTable("patient_care_record", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Person", b =>
                {
                    b.Property<string>("Dni")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("dni");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("fullname");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phonenumber");

                    b.HasKey("Dni");

                    b.ToTable("person", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("invoice_order", b =>
                {
                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersOrderNumber")
                        .HasColumnType("integer");

                    b.HasKey("InvoiceNumber", "OrdersOrderNumber");

                    b.HasIndex("OrdersOrderNumber");

                    b.ToTable("invoice_order");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.DiagnosticAid", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.ClinicalResource");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresSpecialist")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_specialist");

                    b.Property<int?>("SpecialistTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_type_id");

                    b.ToTable("diagnostic_aid", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Medication", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.ClinicalResource");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dose");

                    b.Property<int>("TreatmentDuration")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_duration");

                    b.ToTable("medication", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Procedure", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.ClinicalResource");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<bool>("RequiresSpecialist")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_specialist");

                    b.Property<int?>("SpecialistTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_type_id");

                    b.ToTable("procedure", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.DiagnosticAidOrderItem", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.OrderItem");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<bool>("RequiresSpecialist")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_specialist");

                    b.Property<int?>("SpecialistTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_type_id");

                    b.Property<int?>("diagnostic_aid_id")
                        .HasColumnType("integer");

                    b.HasIndex("diagnostic_aid_id");

                    b.ToTable("diagnostic_aid_order_item", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.MedicationOrderItem", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.OrderItem");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dose");

                    b.Property<int>("TreatmentDuration")
                        .HasColumnType("integer")
                        .HasColumnName("treatment_duration");

                    b.Property<int?>("medication_id")
                        .HasColumnType("integer");

                    b.HasIndex("medication_id");

                    b.ToTable("medication_order_item", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.ProcedureOrderItem", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.OrderItem");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<bool>("RequiresSpecialist")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_specialist");

                    b.Property<int?>("SpecialistTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("specialist_type_id");

                    b.Property<int?>("procedure_id")
                        .HasColumnType("integer");

                    b.HasIndex("procedure_id");

                    b.ToTable("procedure_order_item", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.AdministeredMedication", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.PatientCareRecord");

                    b.Property<string>("AdministrationRoute")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("administration_route");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dose");

                    b.Property<int?>("medication_id")
                        .HasColumnType("integer");

                    b.Property<int?>("nurse_visit_id")
                        .HasColumnType("integer");

                    b.HasIndex("medication_id");

                    b.HasIndex("nurse_visit_id");

                    b.ToTable("administered_medication", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.PerformedProcedure", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.PatientCareRecord");

                    b.ToTable("performed_procedure", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Patient", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.Person");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.User", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.Person");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.NurseVisit", b =>
                {
                    b.HasBaseType("Clinica_Herramientas_2.Domain.Model.PerformedProcedure");

                    b.Property<DateTime>("VisitTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_time");

                    b.Property<string>("nurse_dni")
                        .HasColumnType("character varying(20)");

                    b.Property<string>("patient_dni")
                        .HasColumnType("character varying(20)");

                    b.HasIndex("nurse_dni");

                    b.HasIndex("patient_dni");

                    b.ToTable("nurse_visit", (string)null);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Appointment", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Patient", "Patient1")
                        .WithMany("Appointments")
                        .HasForeignKey("patient_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Patient1");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Invoice", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.User", "Doctor")
                        .WithMany("InvoicesAsDoctor")
                        .HasForeignKey("doctor_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Patient", "Patient")
                        .WithMany("Invoices")
                        .HasForeignKey("patient_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.MedicalRecord", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.User", "Doctor")
                        .WithMany("MedicalRecordsAsDoctor")
                        .HasForeignKey("doctor_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Order", "Order")
                        .WithMany()
                        .HasForeignKey("order_number")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Patient", "Patient")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("patient_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("Order");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.OrderItem", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("order_number")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.PatientCareRecord", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("order_number", "item_number")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("invoice_order", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.DiagnosticAid", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.ClinicalResource", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.DiagnosticAid", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Medication", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.ClinicalResource", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.Medication", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Procedure", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.ClinicalResource", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.Procedure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.DiagnosticAidOrderItem", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.DiagnosticAid", "DiagnosticAid")
                        .WithMany()
                        .HasForeignKey("diagnostic_aid_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.OrderItem", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.DiagnosticAidOrderItem", "OrderNumber", "ItemNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiagnosticAid");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.MedicationOrderItem", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("medication_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.OrderItem", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.MedicationOrderItem", "OrderNumber", "ItemNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.ProcedureOrderItem", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Procedure", "Procedure")
                        .WithMany()
                        .HasForeignKey("procedure_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.OrderItem", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.ProcedureOrderItem", "OrderNumber", "ItemNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Procedure");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.AdministeredMedication", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.PatientCareRecord", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.AdministeredMedication", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Medication", "Medication")
                        .WithMany()
                        .HasForeignKey("medication_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.NurseVisit", null)
                        .WithMany("AdministeredMedications")
                        .HasForeignKey("nurse_visit_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.PerformedProcedure", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.PatientCareRecord", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.PerformedProcedure", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Patient", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Person", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.Patient", "Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Clinica_Herramientas_2.Domain.Model.EmergencyContact", "EmergencyContact", b1 =>
                        {
                            b1.Property<string>("PatientDni")
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Firtname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("emergency_contact_first_name");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("emergency_contact_last_name");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("emergency_contact_phone");

                            b1.Property<string>("Relationship")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("emergency_contact_relationship");

                            b1.HasKey("PatientDni");

                            b1.ToTable("patient");

                            b1.WithOwner()
                                .HasForeignKey("PatientDni");
                        });

                    b.OwnsOne("Clinica_Herramientas_2.Domain.Model.HealthInsurance", "Insurance", b1 =>
                        {
                            b1.Property<string>("PatientDni")
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("CompanyName")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("health_insurance_company");

                            b1.Property<DateTime>("ExpirationDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("health_insurance_expiration");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean")
                                .HasColumnName("health_insurance_active");

                            b1.Property<string>("PolicyNumber")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("health_insurance_policy");

                            b1.HasKey("PatientDni");

                            b1.ToTable("health_insurance");

                            b1.WithOwner()
                                .HasForeignKey("PatientDni");
                        });

                    b.Navigation("EmergencyContact");

                    b.Navigation("Insurance");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.User", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Person", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.User", "Dni")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.NurseVisit", b =>
                {
                    b.HasOne("Clinica_Herramientas_2.Domain.Model.PerformedProcedure", null)
                        .WithOne()
                        .HasForeignKey("Clinica_Herramientas_2.Domain.Model.NurseVisit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.User", "Nurse")
                        .WithMany("NurseVisits")
                        .HasForeignKey("nurse_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinica_Herramientas_2.Domain.Model.Patient", "Patient")
                        .WithMany("NurseVisits")
                        .HasForeignKey("patient_dni")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Clinica_Herramientas_2.Domain.Model.VitalData", "VitalData", b1 =>
                        {
                            b1.Property<int>("NurseVisitId")
                                .HasColumnType("integer");

                            b1.Property<string>("BloodPressure")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("vital_blood_pressure");

                            b1.Property<int>("OxygenLevel")
                                .HasColumnType("integer")
                                .HasColumnName("vital_oxygen_level");

                            b1.Property<int>("Pulse")
                                .HasColumnType("integer")
                                .HasColumnName("vital_pulse");

                            b1.Property<double>("Temperature")
                                .HasColumnType("double precision")
                                .HasColumnName("vital_temperature");

                            b1.HasKey("NurseVisitId");

                            b1.ToTable("nurse_visit");

                            b1.WithOwner()
                                .HasForeignKey("NurseVisitId");
                        });

                    b.Navigation("Nurse");

                    b.Navigation("Patient");

                    b.Navigation("VitalData");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Invoices");

                    b.Navigation("MedicalRecords");

                    b.Navigation("NurseVisits");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.User", b =>
                {
                    b.Navigation("InvoicesAsDoctor");

                    b.Navigation("MedicalRecordsAsDoctor");

                    b.Navigation("NurseVisits");
                });

            modelBuilder.Entity("Clinica_Herramientas_2.Domain.Model.NurseVisit", b =>
                {
                    b.Navigation("AdministeredMedications");
                });
#pragma warning restore 612, 618
        }
    }
}
