namespace Clinica_Herramientas_2.Infrastructure.GUI.Doctor
{
    partial class MedicalRecordForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.grpPatient = new System.Windows.Forms.GroupBox();
            this.lblPatientInfo = new System.Windows.Forms.Label();
            this.btnSelectPatient = new System.Windows.Forms.Button();
            this.grpRecord = new System.Windows.Forms.GroupBox();
            this.txtDiagnosis = new System.Windows.Forms.TextBox();
            this.txtSymptoms = new System.Windows.Forms.TextBox();
            this.txtConsultationReason = new System.Windows.Forms.TextBox();
            this.dtpRecordDate = new System.Windows.Forms.DateTimePicker();
            this.lblDiagnosis = new System.Windows.Forms.Label();
            this.lblSymptoms = new System.Windows.Forms.Label();
            this.lblConsultationReason = new System.Windows.Forms.Label();
            this.lblRecordDate = new System.Windows.Forms.Label();
            this.grpOrder = new System.Windows.Forms.GroupBox();
            this.lblOrderInfo = new System.Windows.Forms.Label();
            this.txtOrderNumber = new System.Windows.Forms.TextBox();
            this.btnCreateOrder = new System.Windows.Forms.Button();
            this.lblOrderNumber = new System.Windows.Forms.Label();
            this.grpOrderItems = new System.Windows.Forms.GroupBox();
            this.lstOrderItems = new System.Windows.Forms.ListBox();
            this.tabOrderItems = new System.Windows.Forms.TabControl();
            this.tabMedication = new System.Windows.Forms.TabPage();
            this.btnAddMedication = new System.Windows.Forms.Button();
            this.txtDuration = new System.Windows.Forms.TextBox();
            this.txtDose = new System.Windows.Forms.TextBox();
            this.cmbMedication = new System.Windows.Forms.ComboBox();
            this.lblDuration = new System.Windows.Forms.Label();
            this.lblDose = new System.Windows.Forms.Label();
            this.lblMedication = new System.Windows.Forms.Label();
            this.tabProcedure = new System.Windows.Forms.TabPage();
            this.txtSpecialistTypeId = new System.Windows.Forms.TextBox();
            this.chkRequiresSpecialist = new System.Windows.Forms.CheckBox();
            this.btnAddProcedure = new System.Windows.Forms.Button();
            this.txtFrequency = new System.Windows.Forms.TextBox();
            this.cmbProcedure = new System.Windows.Forms.ComboBox();
            this.lblSpecialistTypeId = new System.Windows.Forms.Label();
            this.lblFrequency = new System.Windows.Forms.Label();
            this.lblProcedure = new System.Windows.Forms.Label();
            this.tabDiagnosticAid = new System.Windows.Forms.TabPage();
            this.txtDiagSpecialistTypeId = new System.Windows.Forms.TextBox();
            this.chkDiagRequiresSpecialist = new System.Windows.Forms.CheckBox();
            this.btnAddDiagnosticAid = new System.Windows.Forms.Button();
            this.txtQuantity = new System.Windows.Forms.TextBox();
            this.cmbDiagnosticAid = new System.Windows.Forms.ComboBox();
            this.lblDiagSpecialistTypeId = new System.Windows.Forms.Label();
            this.lblQuantity = new System.Windows.Forms.Label();
            this.lblDiagnosticAid = new System.Windows.Forms.Label();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.grpPatient.SuspendLayout();
            this.grpRecord.SuspendLayout();
            this.grpOrder.SuspendLayout();
            this.grpOrderItems.SuspendLayout();
            this.tabOrderItems.SuspendLayout();
            this.tabMedication.SuspendLayout();
            this.tabProcedure.SuspendLayout();
            this.tabDiagnosticAid.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(5, 150, 105);
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(1400, 60);
            this.pnlHeader.TabIndex = 0;
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(20, 18);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(250, 26);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Crear Registro Médico";
            this.grpPatient.Controls.Add(this.lblPatientInfo);
            this.grpPatient.Controls.Add(this.btnSelectPatient);
            this.grpPatient.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpPatient.Location = new System.Drawing.Point(20, 80);
            this.grpPatient.Name = "grpPatient";
            this.grpPatient.Size = new System.Drawing.Size(600, 80);
            this.grpPatient.TabIndex = 1;
            this.grpPatient.TabStop = false;
            this.grpPatient.Text = "Paciente";
            this.btnSelectPatient.BackColor = System.Drawing.Color.FromArgb(5, 150, 105);
            this.btnSelectPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSelectPatient.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.btnSelectPatient.ForeColor = System.Drawing.Color.White;
            this.btnSelectPatient.Location = new System.Drawing.Point(20, 30);
            this.btnSelectPatient.Name = "btnSelectPatient";
            this.btnSelectPatient.Size = new System.Drawing.Size(150, 30);
            this.btnSelectPatient.TabIndex = 0;
            this.btnSelectPatient.Text = "Seleccionar Paciente";
            this.btnSelectPatient.UseVisualStyleBackColor = false;
            this.btnSelectPatient.Click += new System.EventHandler(this.btnSelectPatient_Click);
            this.lblPatientInfo.AutoSize = true;
            this.lblPatientInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblPatientInfo.Location = new System.Drawing.Point(190, 35);
            this.lblPatientInfo.Name = "lblPatientInfo";
            this.lblPatientInfo.Size = new System.Drawing.Size(150, 15);
            this.lblPatientInfo.TabIndex = 1;
            this.lblPatientInfo.Text = "Seleccione un paciente";
            this.grpRecord.Controls.Add(this.txtDiagnosis);
            this.grpRecord.Controls.Add(this.txtSymptoms);
            this.grpRecord.Controls.Add(this.txtConsultationReason);
            this.grpRecord.Controls.Add(this.dtpRecordDate);
            this.grpRecord.Controls.Add(this.lblDiagnosis);
            this.grpRecord.Controls.Add(this.lblSymptoms);
            this.grpRecord.Controls.Add(this.lblConsultationReason);
            this.grpRecord.Controls.Add(this.lblRecordDate);
            this.grpRecord.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpRecord.Location = new System.Drawing.Point(20, 180);
            this.grpRecord.Name = "grpRecord";
            this.grpRecord.Size = new System.Drawing.Size(600, 250);
            this.grpRecord.TabIndex = 2;
            this.grpRecord.TabStop = false;
            this.grpRecord.Text = "Información del Registro";
            this.lblRecordDate.AutoSize = true;
            this.lblRecordDate.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblRecordDate.Location = new System.Drawing.Point(20, 30);
            this.lblRecordDate.Name = "lblRecordDate";
            this.lblRecordDate.Size = new System.Drawing.Size(42, 15);
            this.lblRecordDate.TabIndex = 0;
            this.lblRecordDate.Text = "Fecha:";
            this.dtpRecordDate.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.dtpRecordDate.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpRecordDate.CustomFormat = "dd/MM/yyyy HH:mm";
            this.dtpRecordDate.ShowUpDown = true;
            this.dtpRecordDate.Location = new System.Drawing.Point(68, 27);
            this.dtpRecordDate.Name = "dtpRecordDate";
            this.dtpRecordDate.Size = new System.Drawing.Size(200, 21);
            this.dtpRecordDate.TabIndex = 1;
            this.lblConsultationReason.AutoSize = true;
            this.lblConsultationReason.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblConsultationReason.Location = new System.Drawing.Point(20, 70);
            this.lblConsultationReason.Name = "lblConsultationReason";
            this.lblConsultationReason.Size = new System.Drawing.Size(120, 15);
            this.lblConsultationReason.TabIndex = 2;
            this.lblConsultationReason.Text = "Motivo de Consulta:";
            this.txtConsultationReason.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtConsultationReason.Location = new System.Drawing.Point(150, 67);
            this.txtConsultationReason.Multiline = true;
            this.txtConsultationReason.Name = "txtConsultationReason";
            this.txtConsultationReason.Size = new System.Drawing.Size(430, 50);
            this.txtConsultationReason.TabIndex = 3;
            this.lblSymptoms.AutoSize = true;
            this.lblSymptoms.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblSymptoms.Location = new System.Drawing.Point(20, 130);
            this.lblSymptoms.Name = "lblSymptoms";
            this.lblSymptoms.Size = new System.Drawing.Size(95, 15);
            this.lblSymptoms.TabIndex = 4;
            this.lblSymptoms.Text = "Sintomatología:";
            this.txtSymptoms.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtSymptoms.Location = new System.Drawing.Point(125, 127);
            this.txtSymptoms.Multiline = true;
            this.txtSymptoms.Name = "txtSymptoms";
            this.txtSymptoms.Size = new System.Drawing.Size(455, 50);
            this.txtSymptoms.TabIndex = 5;
            this.lblDiagnosis.AutoSize = true;
            this.lblDiagnosis.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblDiagnosis.Location = new System.Drawing.Point(20, 190);
            this.lblDiagnosis.Name = "lblDiagnosis";
            this.lblDiagnosis.Size = new System.Drawing.Size(75, 15);
            this.lblDiagnosis.TabIndex = 6;
            this.lblDiagnosis.Text = "Diagnóstico:";
            this.txtDiagnosis.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtDiagnosis.Location = new System.Drawing.Point(105, 187);
            this.txtDiagnosis.Multiline = true;
            this.txtDiagnosis.Name = "txtDiagnosis";
            this.txtDiagnosis.Size = new System.Drawing.Size(475, 50);
            this.txtDiagnosis.TabIndex = 7;
            this.grpOrder.Controls.Add(this.lblOrderInfo);
            this.grpOrder.Controls.Add(this.txtOrderNumber);
            this.grpOrder.Controls.Add(this.btnCreateOrder);
            this.grpOrder.Controls.Add(this.lblOrderNumber);
            this.grpOrder.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpOrder.Location = new System.Drawing.Point(640, 80);
            this.grpOrder.Name = "grpOrder";
            this.grpOrder.Size = new System.Drawing.Size(350, 100);
            this.grpOrder.TabIndex = 3;
            this.grpOrder.TabStop = false;
            this.grpOrder.Text = "Orden Médica (Opcional)";
            this.lblOrderNumber.AutoSize = true;
            this.lblOrderNumber.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblOrderNumber.Location = new System.Drawing.Point(20, 30);
            this.lblOrderNumber.Name = "lblOrderNumber";
            this.lblOrderNumber.Size = new System.Drawing.Size(60, 15);
            this.lblOrderNumber.TabIndex = 0;
            this.lblOrderNumber.Text = "Número:";
            this.txtOrderNumber.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtOrderNumber.Location = new System.Drawing.Point(86, 27);
            this.txtOrderNumber.Name = "txtOrderNumber";
            this.txtOrderNumber.Size = new System.Drawing.Size(100, 21);
            this.txtOrderNumber.TabIndex = 1;
            this.btnCreateOrder.BackColor = System.Drawing.Color.FromArgb(34, 197, 94);
            this.btnCreateOrder.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCreateOrder.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.btnCreateOrder.ForeColor = System.Drawing.Color.White;
            this.btnCreateOrder.Location = new System.Drawing.Point(200, 25);
            this.btnCreateOrder.Name = "btnCreateOrder";
            this.btnCreateOrder.Size = new System.Drawing.Size(120, 25);
            this.btnCreateOrder.TabIndex = 2;
            this.btnCreateOrder.Text = "Crear Orden";
            this.btnCreateOrder.UseVisualStyleBackColor = false;
            this.btnCreateOrder.Click += new System.EventHandler(this.btnCreateOrder_Click);
            this.lblOrderInfo.AutoSize = true;
            this.lblOrderInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblOrderInfo.Location = new System.Drawing.Point(20, 65);
            this.lblOrderInfo.Name = "lblOrderInfo";
            this.lblOrderInfo.Size = new System.Drawing.Size(0, 15);
            this.lblOrderInfo.TabIndex = 3;
            this.grpOrderItems.Controls.Add(this.lstOrderItems);
            this.grpOrderItems.Controls.Add(this.tabOrderItems);
            this.grpOrderItems.Enabled = false;
            this.grpOrderItems.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpOrderItems.Location = new System.Drawing.Point(640, 200);
            this.grpOrderItems.Name = "grpOrderItems";
            this.grpOrderItems.Size = new System.Drawing.Size(750, 400);
            this.grpOrderItems.TabIndex = 4;
            this.grpOrderItems.TabStop = false;
            this.grpOrderItems.Text = "Items de la Orden";
            this.tabOrderItems.Controls.Add(this.tabMedication);
            this.tabOrderItems.Controls.Add(this.tabProcedure);
            this.tabOrderItems.Controls.Add(this.tabDiagnosticAid);
            this.tabOrderItems.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.tabOrderItems.Location = new System.Drawing.Point(20, 30);
            this.tabOrderItems.Name = "tabOrderItems";
            this.tabOrderItems.SelectedIndex = 0;
            this.tabOrderItems.Size = new System.Drawing.Size(500, 200);
            this.tabOrderItems.TabIndex = 0;
            this.tabMedication.Controls.Add(this.btnAddMedication);
            this.tabMedication.Controls.Add(this.txtDuration);
            this.tabMedication.Controls.Add(this.txtDose);
            this.tabMedication.Controls.Add(this.cmbMedication);
            this.tabMedication.Controls.Add(this.lblDuration);
            this.tabMedication.Controls.Add(this.lblDose);
            this.tabMedication.Controls.Add(this.lblMedication);
            this.tabMedication.Location = new System.Drawing.Point(4, 24);
            this.tabMedication.Name = "tabMedication";
            this.tabMedication.Padding = new System.Windows.Forms.Padding(3);
            this.tabMedication.Size = new System.Drawing.Size(492, 172);
            this.tabMedication.TabIndex = 0;
            this.tabMedication.Text = "Medicamento";
            this.tabMedication.UseVisualStyleBackColor = true;
            this.lblMedication.AutoSize = true;
            this.lblMedication.Location = new System.Drawing.Point(10, 15);
            this.lblMedication.Name = "lblMedication";
            this.lblMedication.Size = new System.Drawing.Size(75, 15);
            this.lblMedication.TabIndex = 0;
            this.lblMedication.Text = "Medicamento:";
            this.cmbMedication.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbMedication.FormattingEnabled = true;
            this.cmbMedication.Location = new System.Drawing.Point(91, 12);
            this.cmbMedication.Name = "cmbMedication";
            this.cmbMedication.Size = new System.Drawing.Size(350, 23);
            this.cmbMedication.TabIndex = 1;
            this.lblDose.AutoSize = true;
            this.lblDose.Location = new System.Drawing.Point(10, 50);
            this.lblDose.Name = "lblDose";
            this.lblDose.Size = new System.Drawing.Size(40, 15);
            this.lblDose.TabIndex = 2;
            this.lblDose.Text = "Dosis:";
            this.txtDose.Location = new System.Drawing.Point(56, 47);
            this.txtDose.Name = "txtDose";
            this.txtDose.Size = new System.Drawing.Size(200, 21);
            this.txtDose.TabIndex = 3;
            this.lblDuration.AutoSize = true;
            this.lblDuration.Location = new System.Drawing.Point(270, 50);
            this.lblDuration.Name = "lblDuration";
            this.lblDuration.Size = new System.Drawing.Size(60, 15);
            this.lblDuration.TabIndex = 4;
            this.lblDuration.Text = "Duración:";
            this.txtDuration.Location = new System.Drawing.Point(336, 47);
            this.txtDuration.Name = "txtDuration";
            this.txtDuration.Size = new System.Drawing.Size(100, 21);
            this.txtDuration.TabIndex = 5;
            this.btnAddMedication.BackColor = System.Drawing.Color.FromArgb(34, 197, 94);
            this.btnAddMedication.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddMedication.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.btnAddMedication.ForeColor = System.Drawing.Color.White;
            this.btnAddMedication.Location = new System.Drawing.Point(350, 90);
            this.btnAddMedication.Name = "btnAddMedication";
            this.btnAddMedication.Size = new System.Drawing.Size(120, 30);
            this.btnAddMedication.TabIndex = 6;
            this.btnAddMedication.Text = "Agregar";
            this.btnAddMedication.UseVisualStyleBackColor = false;
            this.btnAddMedication.Click += new System.EventHandler(this.btnAddMedication_Click);
            this.tabProcedure.Controls.Add(this.txtSpecialistTypeId);
            this.tabProcedure.Controls.Add(this.chkRequiresSpecialist);
            this.tabProcedure.Controls.Add(this.btnAddProcedure);
            this.tabProcedure.Controls.Add(this.txtFrequency);
            this.tabProcedure.Controls.Add(this.cmbProcedure);
            this.tabProcedure.Controls.Add(this.lblSpecialistTypeId);
            this.tabProcedure.Controls.Add(this.lblFrequency);
            this.tabProcedure.Controls.Add(this.lblProcedure);
            this.tabProcedure.Location = new System.Drawing.Point(4, 24);
            this.tabProcedure.Name = "tabProcedure";
            this.tabProcedure.Padding = new System.Windows.Forms.Padding(3);
            this.tabProcedure.Size = new System.Drawing.Size(492, 172);
            this.tabProcedure.TabIndex = 1;
            this.tabProcedure.Text = "Procedimiento";
            this.tabProcedure.UseVisualStyleBackColor = true;
            this.lblProcedure.AutoSize = true;
            this.lblProcedure.Location = new System.Drawing.Point(10, 15);
            this.lblProcedure.Name = "lblProcedure";
            this.lblProcedure.Size = new System.Drawing.Size(80, 15);
            this.lblProcedure.TabIndex = 0;
            this.lblProcedure.Text = "Procedimiento:";
            this.cmbProcedure.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbProcedure.FormattingEnabled = true;
            this.cmbProcedure.Location = new System.Drawing.Point(96, 12);
            this.cmbProcedure.Name = "cmbProcedure";
            this.cmbProcedure.Size = new System.Drawing.Size(350, 23);
            this.cmbProcedure.TabIndex = 1;
            this.lblFrequency.AutoSize = true;
            this.lblFrequency.Location = new System.Drawing.Point(10, 50);
            this.lblFrequency.Name = "lblFrequency";
            this.lblFrequency.Size = new System.Drawing.Size(68, 15);
            this.lblFrequency.TabIndex = 2;
            this.lblFrequency.Text = "Frecuencia:";
            this.txtFrequency.Location = new System.Drawing.Point(84, 47);
            this.txtFrequency.Name = "txtFrequency";
            this.txtFrequency.Size = new System.Drawing.Size(100, 21);
            this.txtFrequency.TabIndex = 3;
            this.chkRequiresSpecialist.AutoSize = true;
            this.chkRequiresSpecialist.Location = new System.Drawing.Point(200, 49);
            this.chkRequiresSpecialist.Name = "chkRequiresSpecialist";
            this.chkRequiresSpecialist.Size = new System.Drawing.Size(150, 19);
            this.chkRequiresSpecialist.TabIndex = 4;
            this.chkRequiresSpecialist.Text = "Requiere Especialista";
            this.chkRequiresSpecialist.UseVisualStyleBackColor = true;
            this.lblSpecialistTypeId.AutoSize = true;
            this.lblSpecialistTypeId.Location = new System.Drawing.Point(10, 85);
            this.lblSpecialistTypeId.Name = "lblSpecialistTypeId";
            this.lblSpecialistTypeId.Size = new System.Drawing.Size(120, 15);
            this.lblSpecialistTypeId.TabIndex = 5;
            this.lblSpecialistTypeId.Text = "ID Tipo Especialista:";
            this.txtSpecialistTypeId.Enabled = false;
            this.txtSpecialistTypeId.Location = new System.Drawing.Point(136, 82);
            this.txtSpecialistTypeId.Name = "txtSpecialistTypeId";
            this.txtSpecialistTypeId.Size = new System.Drawing.Size(100, 21);
            this.txtSpecialistTypeId.TabIndex = 6;
            this.btnAddProcedure.BackColor = System.Drawing.Color.FromArgb(34, 197, 94);
            this.btnAddProcedure.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddProcedure.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.btnAddProcedure.ForeColor = System.Drawing.Color.White;
            this.btnAddProcedure.Location = new System.Drawing.Point(350, 120);
            this.btnAddProcedure.Name = "btnAddProcedure";
            this.btnAddProcedure.Size = new System.Drawing.Size(120, 30);
            this.btnAddProcedure.TabIndex = 7;
            this.btnAddProcedure.Text = "Agregar";
            this.btnAddProcedure.UseVisualStyleBackColor = false;
            this.btnAddProcedure.Click += new System.EventHandler(this.btnAddProcedure_Click);
            this.tabDiagnosticAid.Controls.Add(this.txtDiagSpecialistTypeId);
            this.tabDiagnosticAid.Controls.Add(this.chkDiagRequiresSpecialist);
            this.tabDiagnosticAid.Controls.Add(this.btnAddDiagnosticAid);
            this.tabDiagnosticAid.Controls.Add(this.txtQuantity);
            this.tabDiagnosticAid.Controls.Add(this.cmbDiagnosticAid);
            this.tabDiagnosticAid.Controls.Add(this.lblDiagSpecialistTypeId);
            this.tabDiagnosticAid.Controls.Add(this.lblQuantity);
            this.tabDiagnosticAid.Controls.Add(this.lblDiagnosticAid);
            this.tabDiagnosticAid.Location = new System.Drawing.Point(4, 24);
            this.tabDiagnosticAid.Name = "tabDiagnosticAid";
            this.tabDiagnosticAid.Padding = new System.Windows.Forms.Padding(3);
            this.tabDiagnosticAid.Size = new System.Drawing.Size(492, 172);
            this.tabDiagnosticAid.TabIndex = 2;
            this.tabDiagnosticAid.Text = "Ayuda Diagnóstica";
            this.tabDiagnosticAid.UseVisualStyleBackColor = true;
            this.lblDiagnosticAid.AutoSize = true;
            this.lblDiagnosticAid.Location = new System.Drawing.Point(10, 15);
            this.lblDiagnosticAid.Name = "lblDiagnosticAid";
            this.lblDiagnosticAid.Size = new System.Drawing.Size(120, 15);
            this.lblDiagnosticAid.TabIndex = 0;
            this.lblDiagnosticAid.Text = "Ayuda Diagnóstica:";
            this.cmbDiagnosticAid.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbDiagnosticAid.FormattingEnabled = true;
            this.cmbDiagnosticAid.Location = new System.Drawing.Point(136, 12);
            this.cmbDiagnosticAid.Name = "cmbDiagnosticAid";
            this.cmbDiagnosticAid.Size = new System.Drawing.Size(350, 23);
            this.cmbDiagnosticAid.TabIndex = 1;
            this.lblQuantity.AutoSize = true;
            this.lblQuantity.Location = new System.Drawing.Point(10, 50);
            this.lblQuantity.Name = "lblQuantity";
            this.lblQuantity.Size = new System.Drawing.Size(60, 15);
            this.lblQuantity.TabIndex = 2;
            this.lblQuantity.Text = "Cantidad:";
            this.txtQuantity.Location = new System.Drawing.Point(76, 47);
            this.txtQuantity.Name = "txtQuantity";
            this.txtQuantity.Size = new System.Drawing.Size(100, 21);
            this.txtQuantity.TabIndex = 3;
            this.chkDiagRequiresSpecialist.AutoSize = true;
            this.chkDiagRequiresSpecialist.Location = new System.Drawing.Point(200, 49);
            this.chkDiagRequiresSpecialist.Name = "chkDiagRequiresSpecialist";
            this.chkDiagRequiresSpecialist.Size = new System.Drawing.Size(150, 19);
            this.chkDiagRequiresSpecialist.TabIndex = 4;
            this.chkDiagRequiresSpecialist.Text = "Requiere Especialista";
            this.chkDiagRequiresSpecialist.UseVisualStyleBackColor = true;
            this.lblDiagSpecialistTypeId.AutoSize = true;
            this.lblDiagSpecialistTypeId.Location = new System.Drawing.Point(10, 85);
            this.lblDiagSpecialistTypeId.Name = "lblDiagSpecialistTypeId";
            this.lblDiagSpecialistTypeId.Size = new System.Drawing.Size(120, 15);
            this.lblDiagSpecialistTypeId.TabIndex = 5;
            this.lblDiagSpecialistTypeId.Text = "ID Tipo Especialista:";
            this.txtDiagSpecialistTypeId.Enabled = false;
            this.txtDiagSpecialistTypeId.Location = new System.Drawing.Point(136, 82);
            this.txtDiagSpecialistTypeId.Name = "txtDiagSpecialistTypeId";
            this.txtDiagSpecialistTypeId.Size = new System.Drawing.Size(100, 21);
            this.txtDiagSpecialistTypeId.TabIndex = 6;
            this.btnAddDiagnosticAid.BackColor = System.Drawing.Color.FromArgb(34, 197, 94);
            this.btnAddDiagnosticAid.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddDiagnosticAid.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.btnAddDiagnosticAid.ForeColor = System.Drawing.Color.White;
            this.btnAddDiagnosticAid.Location = new System.Drawing.Point(350, 120);
            this.btnAddDiagnosticAid.Name = "btnAddDiagnosticAid";
            this.btnAddDiagnosticAid.Size = new System.Drawing.Size(120, 30);
            this.btnAddDiagnosticAid.TabIndex = 7;
            this.btnAddDiagnosticAid.Text = "Agregar";
            this.btnAddDiagnosticAid.UseVisualStyleBackColor = false;
            this.btnAddDiagnosticAid.Click += new System.EventHandler(this.btnAddDiagnosticAid_Click);
            this.lstOrderItems.Dock = System.Windows.Forms.DockStyle.Right;
            this.lstOrderItems.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lstOrderItems.FormattingEnabled = true;
            this.lstOrderItems.ItemHeight = 15;
            this.lstOrderItems.Location = new System.Drawing.Point(540, 30);
            this.lstOrderItems.Name = "lstOrderItems";
            this.lstOrderItems.Size = new System.Drawing.Size(200, 360);
            this.lstOrderItems.TabIndex = 1;
            this.btnSave.BackColor = System.Drawing.Color.FromArgb(5, 150, 105);
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSave.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.Location = new System.Drawing.Point(1100, 620);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(120, 40);
            this.btnSave.TabIndex = 5;
            this.btnSave.Text = "Guardar";
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.btnCancel.BackColor = System.Drawing.Color.FromArgb(156, 163, 175);
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.Location = new System.Drawing.Point(1240, 620);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(120, 40);
            this.btnCancel.TabIndex = 6;
            this.btnCancel.Text = "Cancelar";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(240, 253, 244);
            this.ClientSize = new System.Drawing.Size(1400, 680);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.grpOrderItems);
            this.Controls.Add(this.grpOrder);
            this.Controls.Add(this.grpRecord);
            this.Controls.Add(this.grpPatient);
            this.Controls.Add(this.pnlHeader);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "MedicalRecordForm";
            this.Text = "Crear Registro Médico";
            this.pnlHeader.ResumeLayout(false);
            this.pnlHeader.PerformLayout();
            this.grpPatient.ResumeLayout(false);
            this.grpPatient.PerformLayout();
            this.grpRecord.ResumeLayout(false);
            this.grpRecord.PerformLayout();
            this.grpOrder.ResumeLayout(false);
            this.grpOrder.PerformLayout();
            this.grpOrderItems.ResumeLayout(false);
            this.tabOrderItems.ResumeLayout(false);
            this.tabMedication.ResumeLayout(false);
            this.tabMedication.PerformLayout();
            this.tabProcedure.ResumeLayout(false);
            this.tabProcedure.PerformLayout();
            this.tabDiagnosticAid.ResumeLayout(false);
            this.tabDiagnosticAid.PerformLayout();
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.GroupBox grpPatient;
        private System.Windows.Forms.Button btnSelectPatient;
        private System.Windows.Forms.Label lblPatientInfo;
        private System.Windows.Forms.GroupBox grpRecord;
        private System.Windows.Forms.Label lblRecordDate;
        private System.Windows.Forms.DateTimePicker dtpRecordDate;
        private System.Windows.Forms.Label lblConsultationReason;
        private System.Windows.Forms.TextBox txtConsultationReason;
        private System.Windows.Forms.Label lblSymptoms;
        private System.Windows.Forms.TextBox txtSymptoms;
        private System.Windows.Forms.Label lblDiagnosis;
        private System.Windows.Forms.TextBox txtDiagnosis;
        private System.Windows.Forms.GroupBox grpOrder;
        private System.Windows.Forms.Label lblOrderNumber;
        private System.Windows.Forms.TextBox txtOrderNumber;
        private System.Windows.Forms.Button btnCreateOrder;
        private System.Windows.Forms.Label lblOrderInfo;
        private System.Windows.Forms.GroupBox grpOrderItems;
        private System.Windows.Forms.TabControl tabOrderItems;
        private System.Windows.Forms.TabPage tabMedication;
        private System.Windows.Forms.Label lblMedication;
        private System.Windows.Forms.ComboBox cmbMedication;
        private System.Windows.Forms.Label lblDose;
        private System.Windows.Forms.TextBox txtDose;
        private System.Windows.Forms.Label lblDuration;
        private System.Windows.Forms.TextBox txtDuration;
        private System.Windows.Forms.Button btnAddMedication;
        private System.Windows.Forms.TabPage tabProcedure;
        private System.Windows.Forms.Label lblProcedure;
        private System.Windows.Forms.ComboBox cmbProcedure;
        private System.Windows.Forms.Label lblFrequency;
        private System.Windows.Forms.TextBox txtFrequency;
        private System.Windows.Forms.CheckBox chkRequiresSpecialist;
        private System.Windows.Forms.Label lblSpecialistTypeId;
        private System.Windows.Forms.TextBox txtSpecialistTypeId;
        private System.Windows.Forms.Button btnAddProcedure;
        private System.Windows.Forms.TabPage tabDiagnosticAid;
        private System.Windows.Forms.Label lblDiagnosticAid;
        private System.Windows.Forms.ComboBox cmbDiagnosticAid;
        private System.Windows.Forms.Label lblQuantity;
        private System.Windows.Forms.TextBox txtQuantity;
        private System.Windows.Forms.CheckBox chkDiagRequiresSpecialist;
        private System.Windows.Forms.Label lblDiagSpecialistTypeId;
        private System.Windows.Forms.TextBox txtDiagSpecialistTypeId;
        private System.Windows.Forms.Button btnAddDiagnosticAid;
        private System.Windows.Forms.ListBox lstOrderItems;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnCancel;
    }
}

