namespace Clinica_Herramientas_2.Infrastructure.GUI.Nurse
{
    partial class NurseVisitForm
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing) { if (disposing && (components != null)) components.Dispose(); base.Dispose(disposing); }
        private void InitializeComponent()
        {
            this.pnlHeader = new System.Windows.Forms.Panel();
            this.lblTitle = new System.Windows.Forms.Label();
            this.grpPatient = new System.Windows.Forms.GroupBox();
            this.lblPatientInfo = new System.Windows.Forms.Label();
            this.btnSelectPatient = new System.Windows.Forms.Button();
            this.grpOrder = new System.Windows.Forms.GroupBox();
            this.cmbOrderItem = new System.Windows.Forms.ComboBox();
            this.lblOrderItem = new System.Windows.Forms.Label();
            this.grpVitals = new System.Windows.Forms.GroupBox();
            this.txtOxygenLevel = new System.Windows.Forms.TextBox();
            this.txtPulse = new System.Windows.Forms.TextBox();
            this.txtTemperature = new System.Windows.Forms.TextBox();
            this.txtBloodPressure = new System.Windows.Forms.TextBox();
            this.lblOxygenLevel = new System.Windows.Forms.Label();
            this.lblPulse = new System.Windows.Forms.Label();
            this.lblTemperature = new System.Windows.Forms.Label();
            this.lblBloodPressure = new System.Windows.Forms.Label();
            this.grpVisit = new System.Windows.Forms.GroupBox();
            this.dtpVisitTime = new System.Windows.Forms.DateTimePicker();
            this.dtpPerformedAt = new System.Windows.Forms.DateTimePicker();
            this.txtNotes = new System.Windows.Forms.TextBox();
            this.txtTestsPerformed = new System.Windows.Forms.TextBox();
            this.lblVisitTime = new System.Windows.Forms.Label();
            this.lblPerformedAt = new System.Windows.Forms.Label();
            this.lblNotes = new System.Windows.Forms.Label();
            this.lblTestsPerformed = new System.Windows.Forms.Label();
            this.grpMedication = new System.Windows.Forms.GroupBox();
            this.lstMedications = new System.Windows.Forms.ListBox();
            this.btnAddMedication = new System.Windows.Forms.Button();
            this.txtRoute = new System.Windows.Forms.TextBox();
            this.txtDose = new System.Windows.Forms.TextBox();
            this.lblRoute = new System.Windows.Forms.Label();
            this.lblDose = new System.Windows.Forms.Label();
            this.btnSave = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            this.pnlHeader.SuspendLayout();
            this.grpPatient.SuspendLayout();
            this.grpOrder.SuspendLayout();
            this.grpVitals.SuspendLayout();
            this.grpVisit.SuspendLayout();
            this.grpMedication.SuspendLayout();
            this.SuspendLayout();
            this.pnlHeader.BackColor = System.Drawing.Color.FromArgb(236, 72, 153);
            this.pnlHeader.Controls.Add(this.lblTitle);
            this.pnlHeader.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlHeader.Location = new System.Drawing.Point(0, 0);
            this.pnlHeader.Name = "pnlHeader";
            this.pnlHeader.Size = new System.Drawing.Size(1200, 60);
            this.pnlHeader.TabIndex = 0;
            this.lblTitle.AutoSize = true;
            this.lblTitle.Font = new System.Drawing.Font("Microsoft Sans Serif", 16F, System.Drawing.FontStyle.Bold);
            this.lblTitle.ForeColor = System.Drawing.Color.White;
            this.lblTitle.Location = new System.Drawing.Point(20, 18);
            this.lblTitle.Name = "lblTitle";
            this.lblTitle.Size = new System.Drawing.Size(200, 26);
            this.lblTitle.TabIndex = 0;
            this.lblTitle.Text = "Registrar Visita";
            this.grpPatient.Controls.Add(this.lblPatientInfo);
            this.grpPatient.Controls.Add(this.btnSelectPatient);
            this.grpPatient.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpPatient.Location = new System.Drawing.Point(20, 80);
            this.grpPatient.Name = "grpPatient";
            this.grpPatient.Size = new System.Drawing.Size(600, 80);
            this.grpPatient.TabIndex = 1;
            this.grpPatient.TabStop = false;
            this.grpPatient.Text = "Paciente";
            this.btnSelectPatient.BackColor = System.Drawing.Color.FromArgb(236, 72, 153);
            this.btnSelectPatient.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSelectPatient.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.btnSelectPatient.ForeColor = System.Drawing.Color.White;
            this.btnSelectPatient.Location = new System.Drawing.Point(20, 30);
            this.btnSelectPatient.Name = "btnSelectPatient";
            this.btnSelectPatient.Size = new System.Drawing.Size(150, 30);
            this.btnSelectPatient.TabIndex = 0;
            this.btnSelectPatient.Text = "Seleccionar Paciente";
            this.btnSelectPatient.UseVisualStyleBackColor = false;
            this.btnSelectPatient.Click += new System.EventHandler(this.btnSelectPatient_Click);
            this.lblPatientInfo.AutoSize = true;
            this.lblPatientInfo.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblPatientInfo.Location = new System.Drawing.Point(190, 35);
            this.lblPatientInfo.Name = "lblPatientInfo";
            this.lblPatientInfo.Size = new System.Drawing.Size(150, 15);
            this.lblPatientInfo.TabIndex = 1;
            this.lblPatientInfo.Text = "Seleccione un paciente";
            this.grpOrder.Controls.Add(this.cmbOrderItem);
            this.grpOrder.Controls.Add(this.lblOrderItem);
            this.grpOrder.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpOrder.Location = new System.Drawing.Point(640, 80);
            this.grpOrder.Name = "grpOrder";
            this.grpOrder.Size = new System.Drawing.Size(550, 80);
            this.grpOrder.TabIndex = 2;
            this.grpOrder.TabStop = false;
            this.grpOrder.Text = "Item de Orden";
            this.lblOrderItem.AutoSize = true;
            this.lblOrderItem.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblOrderItem.Location = new System.Drawing.Point(20, 35);
            this.lblOrderItem.Name = "lblOrderItem";
            this.lblOrderItem.Size = new System.Drawing.Size(80, 15);
            this.lblOrderItem.TabIndex = 0;
            this.lblOrderItem.Text = "Item de Orden:";
            this.cmbOrderItem.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cmbOrderItem.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.cmbOrderItem.FormattingEnabled = true;
            this.cmbOrderItem.Location = new System.Drawing.Point(110, 32);
            this.cmbOrderItem.Name = "cmbOrderItem";
            this.cmbOrderItem.Size = new System.Drawing.Size(420, 23);
            this.cmbOrderItem.TabIndex = 1;
            this.cmbOrderItem.SelectedIndexChanged += new System.EventHandler(this.cmbOrderItem_SelectedIndexChanged);
            this.grpVitals.Controls.Add(this.txtOxygenLevel);
            this.grpVitals.Controls.Add(this.txtPulse);
            this.grpVitals.Controls.Add(this.txtTemperature);
            this.grpVitals.Controls.Add(this.txtBloodPressure);
            this.grpVitals.Controls.Add(this.lblOxygenLevel);
            this.grpVitals.Controls.Add(this.lblPulse);
            this.grpVitals.Controls.Add(this.lblTemperature);
            this.grpVitals.Controls.Add(this.lblBloodPressure);
            this.grpVitals.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpVitals.Location = new System.Drawing.Point(20, 180);
            this.grpVitals.Name = "grpVitals";
            this.grpVitals.Size = new System.Drawing.Size(600, 150);
            this.grpVitals.TabIndex = 3;
            this.grpVitals.TabStop = false;
            this.grpVitals.Text = "Signos Vitales";
            this.lblBloodPressure.AutoSize = true;
            this.lblBloodPressure.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblBloodPressure.Location = new System.Drawing.Point(20, 30);
            this.lblBloodPressure.Name = "lblBloodPressure";
            this.lblBloodPressure.Size = new System.Drawing.Size(120, 15);
            this.lblBloodPressure.TabIndex = 0;
            this.lblBloodPressure.Text = "Presión Arterial:";
            this.txtBloodPressure.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtBloodPressure.Location = new System.Drawing.Point(150, 27);
            this.txtBloodPressure.Name = "txtBloodPressure";
            this.txtBloodPressure.Size = new System.Drawing.Size(200, 21);
            this.txtBloodPressure.TabIndex = 1;
            this.lblTemperature.AutoSize = true;
            this.lblTemperature.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblTemperature.Location = new System.Drawing.Point(20, 65);
            this.lblTemperature.Name = "lblTemperature";
            this.lblTemperature.Size = new System.Drawing.Size(75, 15);
            this.lblTemperature.TabIndex = 2;
            this.lblTemperature.Text = "Temperatura:";
            this.txtTemperature.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtTemperature.Location = new System.Drawing.Point(105, 62);
            this.txtTemperature.Name = "txtTemperature";
            this.txtTemperature.Size = new System.Drawing.Size(150, 21);
            this.txtTemperature.TabIndex = 3;
            this.lblPulse.AutoSize = true;
            this.lblPulse.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblPulse.Location = new System.Drawing.Point(280, 65);
            this.lblPulse.Name = "lblPulse";
            this.lblPulse.Size = new System.Drawing.Size(45, 15);
            this.lblPulse.TabIndex = 4;
            this.lblPulse.Text = "Pulso:";
            this.txtPulse.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtPulse.Location = new System.Drawing.Point(331, 62);
            this.txtPulse.Name = "txtPulse";
            this.txtPulse.Size = new System.Drawing.Size(100, 21);
            this.txtPulse.TabIndex = 5;
            this.lblOxygenLevel.AutoSize = true;
            this.lblOxygenLevel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblOxygenLevel.Location = new System.Drawing.Point(20, 100);
            this.lblOxygenLevel.Name = "lblOxygenLevel";
            this.lblOxygenLevel.Size = new System.Drawing.Size(120, 15);
            this.lblOxygenLevel.TabIndex = 6;
            this.lblOxygenLevel.Text = "Nivel de Oxígeno:";
            this.txtOxygenLevel.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtOxygenLevel.Location = new System.Drawing.Point(150, 97);
            this.txtOxygenLevel.Name = "txtOxygenLevel";
            this.txtOxygenLevel.Size = new System.Drawing.Size(100, 21);
            this.txtOxygenLevel.TabIndex = 7;
            this.grpVisit.Controls.Add(this.dtpVisitTime);
            this.grpVisit.Controls.Add(this.dtpPerformedAt);
            this.grpVisit.Controls.Add(this.txtNotes);
            this.grpVisit.Controls.Add(this.txtTestsPerformed);
            this.grpVisit.Controls.Add(this.lblVisitTime);
            this.grpVisit.Controls.Add(this.lblPerformedAt);
            this.grpVisit.Controls.Add(this.lblNotes);
            this.grpVisit.Controls.Add(this.lblTestsPerformed);
            this.grpVisit.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpVisit.Location = new System.Drawing.Point(640, 180);
            this.grpVisit.Name = "grpVisit";
            this.grpVisit.Size = new System.Drawing.Size(550, 200);
            this.grpVisit.TabIndex = 4;
            this.grpVisit.TabStop = false;
            this.grpVisit.Text = "Información de la Visita";
            this.lblTestsPerformed.AutoSize = true;
            this.lblTestsPerformed.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblTestsPerformed.Location = new System.Drawing.Point(20, 30);
            this.lblTestsPerformed.Name = "lblTestsPerformed";
            this.lblTestsPerformed.Size = new System.Drawing.Size(100, 15);
            this.lblTestsPerformed.TabIndex = 0;
            this.lblTestsPerformed.Text = "Pruebas Realizadas:";
            this.txtTestsPerformed.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtTestsPerformed.Location = new System.Drawing.Point(130, 27);
            this.txtTestsPerformed.Multiline = true;
            this.txtTestsPerformed.Name = "txtTestsPerformed";
            this.txtTestsPerformed.Size = new System.Drawing.Size(400, 50);
            this.txtTestsPerformed.TabIndex = 1;
            this.lblNotes.AutoSize = true;
            this.lblNotes.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblNotes.Location = new System.Drawing.Point(20, 90);
            this.lblNotes.Name = "lblNotes";
            this.lblNotes.Size = new System.Drawing.Size(50, 15);
            this.lblNotes.TabIndex = 2;
            this.lblNotes.Text = "Notas:";
            this.txtNotes.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtNotes.Location = new System.Drawing.Point(80, 87);
            this.txtNotes.Multiline = true;
            this.txtNotes.Name = "txtNotes";
            this.txtNotes.Size = new System.Drawing.Size(450, 50);
            this.txtNotes.TabIndex = 3;
            this.lblPerformedAt.AutoSize = true;
            this.lblPerformedAt.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblPerformedAt.Location = new System.Drawing.Point(20, 150);
            this.lblPerformedAt.Name = "lblPerformedAt";
            this.lblPerformedAt.Size = new System.Drawing.Size(100, 15);
            this.lblPerformedAt.TabIndex = 4;
            this.lblPerformedAt.Text = "Fecha Realización:";
            this.dtpPerformedAt.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.dtpPerformedAt.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpPerformedAt.CustomFormat = "dd/MM/yyyy HH:mm";
            this.dtpPerformedAt.ShowUpDown = true;
            this.dtpPerformedAt.Location = new System.Drawing.Point(130, 147);
            this.dtpPerformedAt.Name = "dtpPerformedAt";
            this.dtpPerformedAt.Size = new System.Drawing.Size(200, 21);
            this.dtpPerformedAt.TabIndex = 5;
            this.lblVisitTime.AutoSize = true;
            this.lblVisitTime.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblVisitTime.Location = new System.Drawing.Point(350, 150);
            this.lblVisitTime.Name = "lblVisitTime";
            this.lblVisitTime.Size = new System.Drawing.Size(90, 15);
            this.lblVisitTime.TabIndex = 6;
            this.lblVisitTime.Text = "Hora de Visita:";
            this.dtpVisitTime.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.dtpVisitTime.Format = System.Windows.Forms.DateTimePickerFormat.Custom;
            this.dtpVisitTime.CustomFormat = "dd/MM/yyyy HH:mm";
            this.dtpVisitTime.ShowUpDown = true;
            this.dtpVisitTime.Location = new System.Drawing.Point(450, 147);
            this.dtpVisitTime.Name = "dtpVisitTime";
            this.dtpVisitTime.Size = new System.Drawing.Size(200, 21);
            this.dtpVisitTime.TabIndex = 7;
            this.grpMedication.Controls.Add(this.lstMedications);
            this.grpMedication.Controls.Add(this.btnAddMedication);
            this.grpMedication.Controls.Add(this.txtRoute);
            this.grpMedication.Controls.Add(this.txtDose);
            this.grpMedication.Controls.Add(this.lblRoute);
            this.grpMedication.Controls.Add(this.lblDose);
            this.grpMedication.Font = new System.Drawing.Font("Microsoft Sans Serif", 10F, System.Drawing.FontStyle.Bold);
            this.grpMedication.Location = new System.Drawing.Point(20, 350);
            this.grpMedication.Name = "grpMedication";
            this.grpMedication.Size = new System.Drawing.Size(1170, 200);
            this.grpMedication.TabIndex = 5;
            this.grpMedication.TabStop = false;
            this.grpMedication.Text = "Medicamentos Administrados";
            this.lblDose.AutoSize = true;
            this.lblDose.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblDose.Location = new System.Drawing.Point(20, 30);
            this.lblDose.Name = "lblDose";
            this.lblDose.Size = new System.Drawing.Size(40, 15);
            this.lblDose.TabIndex = 0;
            this.lblDose.Text = "Dosis:";
            this.txtDose.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtDose.Location = new System.Drawing.Point(66, 27);
            this.txtDose.Name = "txtDose";
            this.txtDose.Size = new System.Drawing.Size(200, 21);
            this.txtDose.TabIndex = 1;
            this.lblRoute.AutoSize = true;
            this.lblRoute.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lblRoute.Location = new System.Drawing.Point(280, 30);
            this.lblRoute.Name = "lblRoute";
            this.lblRoute.Size = new System.Drawing.Size(120, 15);
            this.lblRoute.TabIndex = 2;
            this.lblRoute.Text = "Vía de Administración:";
            this.txtRoute.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.txtRoute.Location = new System.Drawing.Point(410, 27);
            this.txtRoute.Name = "txtRoute";
            this.txtRoute.Size = new System.Drawing.Size(200, 21);
            this.txtRoute.TabIndex = 3;
            this.btnAddMedication.BackColor = System.Drawing.Color.FromArgb(34, 197, 94);
            this.btnAddMedication.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnAddMedication.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold);
            this.btnAddMedication.ForeColor = System.Drawing.Color.White;
            this.btnAddMedication.Location = new System.Drawing.Point(630, 25);
            this.btnAddMedication.Name = "btnAddMedication";
            this.btnAddMedication.Size = new System.Drawing.Size(120, 25);
            this.btnAddMedication.TabIndex = 4;
            this.btnAddMedication.Text = "Agregar";
            this.btnAddMedication.UseVisualStyleBackColor = false;
            this.btnAddMedication.Click += new System.EventHandler(this.btnAddMedication_Click);
            this.lstMedications.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F);
            this.lstMedications.FormattingEnabled = true;
            this.lstMedications.ItemHeight = 15;
            this.lstMedications.Location = new System.Drawing.Point(20, 60);
            this.lstMedications.Name = "lstMedications";
            this.lstMedications.Size = new System.Drawing.Size(1130, 124);
            this.lstMedications.TabIndex = 5;
            this.btnSave.BackColor = System.Drawing.Color.FromArgb(236, 72, 153);
            this.btnSave.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnSave.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.Location = new System.Drawing.Point(950, 570);
            this.btnSave.Name = "btnSave";
            this.btnSave.Size = new System.Drawing.Size(120, 40);
            this.btnSave.TabIndex = 6;
            this.btnSave.Text = "Guardar";
            this.btnSave.UseVisualStyleBackColor = false;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.btnCancel.BackColor = System.Drawing.Color.FromArgb(156, 163, 175);
            this.btnCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnCancel.Font = new System.Drawing.Font("Microsoft Sans Serif", 11F, System.Drawing.FontStyle.Bold);
            this.btnCancel.ForeColor = System.Drawing.Color.White;
            this.btnCancel.Location = new System.Drawing.Point(1090, 570);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(120, 40);
            this.btnCancel.TabIndex = 7;
            this.btnCancel.Text = "Cancelar";
            this.btnCancel.UseVisualStyleBackColor = false;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(253, 242, 248);
            this.ClientSize = new System.Drawing.Size(1200, 630);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.grpMedication);
            this.Controls.Add(this.grpVisit);
            this.Controls.Add(this.grpVitals);
            this.Controls.Add(this.grpOrder);
            this.Controls.Add(this.grpPatient);
            this.Controls.Add(this.pnlHeader);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "NurseVisitForm";
            this.Text = "Registrar Visita";
            this.pnlHeader.ResumeLayout(false);
            this.pnlHeader.PerformLayout();
            this.grpPatient.ResumeLayout(false);
            this.grpPatient.PerformLayout();
            this.grpOrder.ResumeLayout(false);
            this.grpOrder.PerformLayout();
            this.grpVitals.ResumeLayout(false);
            this.grpVitals.PerformLayout();
            this.grpVisit.ResumeLayout(false);
            this.grpVisit.PerformLayout();
            this.grpMedication.ResumeLayout(false);
            this.grpMedication.PerformLayout();
            this.ResumeLayout(false);
        }
        private System.Windows.Forms.Panel pnlHeader;
        private System.Windows.Forms.Label lblTitle;
        private System.Windows.Forms.GroupBox grpPatient;
        private System.Windows.Forms.Button btnSelectPatient;
        private System.Windows.Forms.Label lblPatientInfo;
        private System.Windows.Forms.GroupBox grpOrder;
        private System.Windows.Forms.Label lblOrderItem;
        private System.Windows.Forms.ComboBox cmbOrderItem;
        private System.Windows.Forms.GroupBox grpVitals;
        private System.Windows.Forms.Label lblBloodPressure;
        private System.Windows.Forms.TextBox txtBloodPressure;
        private System.Windows.Forms.Label lblTemperature;
        private System.Windows.Forms.TextBox txtTemperature;
        private System.Windows.Forms.Label lblPulse;
        private System.Windows.Forms.TextBox txtPulse;
        private System.Windows.Forms.Label lblOxygenLevel;
        private System.Windows.Forms.TextBox txtOxygenLevel;
        private System.Windows.Forms.GroupBox grpVisit;
        private System.Windows.Forms.Label lblTestsPerformed;
        private System.Windows.Forms.TextBox txtTestsPerformed;
        private System.Windows.Forms.Label lblNotes;
        private System.Windows.Forms.TextBox txtNotes;
        private System.Windows.Forms.Label lblPerformedAt;
        private System.Windows.Forms.DateTimePicker dtpPerformedAt;
        private System.Windows.Forms.Label lblVisitTime;
        private System.Windows.Forms.DateTimePicker dtpVisitTime;
        private System.Windows.Forms.GroupBox grpMedication;
        private System.Windows.Forms.Label lblDose;
        private System.Windows.Forms.TextBox txtDose;
        private System.Windows.Forms.Label lblRoute;
        private System.Windows.Forms.TextBox txtRoute;
        private System.Windows.Forms.Button btnAddMedication;
        private System.Windows.Forms.ListBox lstMedications;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.Button btnCancel;
    }
}

